config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html

  root 'galleries#index', as: 'home'

  resources :users

  resources :galleries

  resources :images, except: [:edit, :update] do
    collection do
      patch :sort
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions', to: 'sessions#new'

  get 'me', to: 'pages#me'

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unprocessable_entity'
  get '500', to: 'errors#internal_server_error'
end

app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy

  validates :name,
            presence: true,
            length:   { minimum: 3, maximum: 50 }

  validates :description,
            length: { maximum: 255 }

  ##
  # Is the parameter User approved to perform edits to this record?
  #
  # @param comparison_user [User]
  #   User that is requesting write access to this record.
  #   This is most likely to be the `current_user`
  #
  def authorised?(comparison_user)
    return false unless comparison_user

    comparison_user.id == user.id
  end
end

app/controllers/galleries_controller.rb
# frozen_string_literal: true

class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[show edit update destroy]
  before_action :authorised_only, only: %i[edit update destroy]
  before_action :logged_in_only, only: %i[new create]

  # GET /galleries
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  def show; end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # POST /galleries
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user = current_user

    if @gallery.save
      redirect_to edit_gallery_path(@gallery)
    else
      render 'new'
    end
  end

  # GET /galleries/1/edit
  def edit
    # If arriving from 'ImagesController#create'
    @image_errors = session[:image_errors]
    session[:image_errors] = nil

    # This is the view where the images are uploaded
    @image = Image.new
  end

  # PATCH/PUT /galleries/1
  def update
    if @gallery.update(gallery_params)
      flash[:collapse_toggle] = nil
      redirect_to edit_gallery_path(@gallery)
    else
      flash[:collapse_toggle] = 'show'
      render 'edit'
    end
  end

  # DELETE /galleries/1
  def destroy
    @gallery.destroy

    redirect_to galleries_path
  end

  private

  # Set the gallery based on the parameters sent
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Allow only parameters from the whitelist
  def gallery_params
    params.require(:gallery).permit(:name, :description)
  end

  # Redirect an action if the current user is not authorised
  def authorised_only
    return if @gallery.authorised?(current_user)

    # If they are logged in (but as the wrong user)
    if current_user
      flash[:alert] = 'Users can only amend their own galleries'
      redirect_to home_url

    # If they are not logged in
    else
      flash[:alert] = 'To amend gallery details, please log in'
      redirect_to login_url
    end
  end

  # Redirect an action if the current user is not logged in
  def logged_in_only
    return if current_user

    flash[:alert] = 'To create a gallery, please log in'
    redirect_to login_url
  end
end

app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

app/views/galleries/_card.html.erb
<%#

Render a single gallery as a Bootstrap card.
Editing routes are only visible if the 'current_user' owns the gallery.

@param [Gallery] gallery
  The gallery to be displayed

%>
<div class="col-md-3">
  <div class="card mb-3 shadow-sm">
    <a href="<%= gallery_path(gallery) %>">
      <%= display_thumbnail(gallery.images.first) %>
    </a>
    <div class="card-body">
      <p class="card-text"><%= gallery.name %></p>
      <div class="d-flex justify-content-between a.lign-items-center">
        <div class="btn-group">

          <%# Only gallery's owner can edit or delete gallery %>
          <% if gallery.user == current_user %>
            <%= link_to('View', gallery_path(gallery), class: 'btn btn-sm btn-outline-secondary')%>
            <%= link_to('Edit', edit_gallery_path(gallery), class: 'btn btn-sm btn-outline-secondary')%>
            <%= link_to('Delete', gallery_path(gallery), method: :delete, class: 'btn btn-sm btn-outline-secondary', data: {confirm: "This will delete the chosen gallery, including all images.\nAre you sure you want to do this?"})%>
          <% end %>

        </div>

        <% if gallery.user != current_user %>
          <small class="text-muted">
            by <%= link_to(gallery.user.username, user_path(gallery.user), class: 'text-muted')%>
          </small>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/galleries/_form.html.erb
<div class="container" style="max-width: 800px;">
  <%= form_for(@gallery, :html => {class: "form-horizontal center"}) do |f| %>
    <div class="container" style="max-width: 480px;">
      <div class="form-group">
        <%= f.label 'Gallery Name' %>
        <%= f.text_field :name, {class: 'form-control', placeholder: 'Name'} %>
      </div>
      <div class="form-group">
        <%= f.label 'Gallery Description' %>
        <%= f.text_area :description, {class: 'form-control', placeholder: 'Description'} %>
      </div>
      <div>
        <%= f.submit(submit_text, {class: 'btn btn-lg btn-primary'}) %>
      </div>
    </div>
  <% end %>
</div>

app/views/galleries/edit.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <%= render 'application/show_errors', error_messages: @gallery.errors.full_messages %>

    <%# TODO: This is fairly hideous %>
    <%# How are we supposed to capture the initial saved field values? %>
    <%# And why can't I read '@gallery.changes' from the controller? %>
    <h1 class="jumbotron-heading">
      <%= @gallery.changes['name']&.first || @gallery.name %>
    </h1>
    <p class="lead text-muted">
      <%= @gallery.changes['description']&.first || @gallery.description %>
    </p>

    <%# Hide the edit form unless user wants to edit %>
    <p>
      <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#edit-gallery" aria-expanded="false" aria-controls="edit-gallery">
        Edit gallery info
      </button>

      <%# Use the flash hash to uncollapse on page load %>
      <div class="collapse <%= flash[:collapse_toggle] %>" id="edit-gallery">
        <%= render 'galleries/form', submit_text: 'Update gallery info' %>
      </div>

    </p>
    <p><%= link_to('View gallery', gallery_path(@gallery), class: 'btn btn-secondary') %></p>
    <p><%= link_to('Delete this gallery', gallery_path(@gallery), method: :delete, class: 'btn btn-danger', data: {confirm: "This will delete the entire gallery, including all images.\nAre you sure you want to do this?"})%></p>

    <hr>

    <div class="container" style="max-width: 800px;">
      <%= render 'application/show_errors', error_messages: @image_errors %>

      <%= form_for(@gallery.images.build, :html => {class: "input-group mb-3"}) do |f| %>
        <%= f.hidden_field(:gallery_id, :value => @gallery.id) %>
        <div class="input-group-prepend">
          <span class="input-group-text">Upload new image:</span>
        </div>
        <div class="custom-file">
          <%= f.file_field(:file, {accept: 'image/*', class: 'custom-file-input'}) %>
          <%= f.label 'Choose file', {class: 'custom-file-label text-left'} %>
        </div>
        <div>
          <%= f.submit('Add image', {class: 'btn btn-primary ml-2'}) %>
        </div>
      <% end %>

    </div>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <p class="lead text-muted text-right">
      Drag and drop images to change their order
    </p>

    <div class="row" id="sort_images" data-url="<%= sort_images_path %>">
      <% @gallery.images.each do |image| %>
        <%# This feels a bit hacky... %>
        <% next unless image.created_at? %>

        <%= render 'images/card', image: image %>
      <% end %>
    </div>

  </div>
</div>

app/views/galleries/index.html.erb
<section class="jumbotron text-center">
  <div class="container">

    <%# If there is an alert to display: %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice %>
      <div class="alert alert-primary" role="notice">
        <%= notice %>
      </div>
    <% end %>

    <h1 class="jumbotron-heading">Galleries</h1>

    <%# If User is logged in: %>
    <% if current_user %>
      <p class="lead text-muted">
        Take a look at galleries by other awesome users.
      </p>
      <p>
        <%= link_to('Create new gallery', new_gallery_path, class: 'btn btn-lg btn-primary mt-3') %>
      </p>

    <%# If User is not logged in: %>
    <% else %>
      <p class="lead text-muted">
        All these people are sharing their memories.
      </p>
      <p>
        <%= link_to('Sign up to add your own', signup_path, class: 'btn btn-lg btn-primary mt-3') %>
      </p>
    <% end %>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">

      <% if @galleries.empty? %>
        <p>There are no galleries yet.</p>

      <% else %>
        <% @galleries.each do |gallery| %>
          <%= render 'galleries/card', gallery: gallery %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/galleries/new.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <%= render 'application/show_errors', error_messages: @gallery.errors.full_messages %>

    <h1 class="jumbotron-heading">Create a gallery!</h1>
    <p class="lead text-muted">
      A gallery is a great way for you to share photos with your friends.
      <br>
      Just give it a name and a description, and then start adding photos!
      <br>
      <br>
      The name should be something like "2018 trip to Paris", or "Sally's birthday".
      <br>
      For the description, maybe describe your holiday, or what Sally got up to that night.
    </p>
    <%= render 'galleries/form', submit_text: 'Create new gallery' %>
    <%= link_to('Cancel', user_path(current_user), class: 'btn btn-secondary mt-3') %>
  </div class="container">
</section>

app/views/galleries/show.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= @gallery.name %></h1>
    <p class="lead text-muted"><%= @gallery.description %></p>
    <p class="lead text-muted">by <%= link_to(@gallery.user.username, user_path(@gallery.user))%></p>
    <p class="lead text-muted">
      Gallery contains <strong><%= @gallery.images.count %></strong> <%= 'image'.pluralize(@images_count) %>
    </p>

    <%# Only current user can edit gallery %>
    <% if @gallery.authorised?(current_user) %>
      <p>
        <%= link_to('Edit this gallery', edit_gallery_path(@gallery), class: 'btn btn-lg btn-primary mt-3') %>
      </p>
    <% end %>

  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

    <% if @gallery.images.empty? %>
      <% if @gallery.authorised?(current_user) %>
        <p>There are no images in this gallery. Why not <a href="<%= edit_gallery_path(@gallery) %>">add some</a>?</p>
      <% else %>
        <p>There are no images in this gallery.</p>
      <% end %>
    <% end %>

    <div class="row">
      <% @gallery.images.each do |image| %>
        <%= render 'images/card', image: image %>
      <% end %>
    </div>

  </div>
</div>