config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html

  root 'galleries#index', as: 'home'

  resources :users

  resources :galleries

  resources :images, except: [:edit, :update] do
    collection do
      patch :sort
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions', to: 'sessions#new'

  get 'me', to: 'pages#me'

  get '404', to: 'errors#not_found'
  get '422', to: 'errors#unprocessable_entity'
  get '500', to: 'errors#internal_server_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="<%= home_path %>" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Rails Gallery</strong>
          </a>

          <div class="navbar-text d-flex align-items-center">
            <nav class="my-2 my-md-0 mr-md-3">
              <a class="p-2" href="<%= users_path %>">Users</a>
              <a class="p-2" href="<%= galleries_path %>">Galleries</a>
              <a class="p-2" href="<%= images_path %>">Images</a>
            </nav>
          </div>

          <%# If User is logged in: %>
          <% if current_user %>
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Logged in as:&nbsp;&nbsp;&nbsp;<strong><%= current_user.username %></strong>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%= me_path %>">View My Profile</a>
                <a class="dropdown-item" href="<%= new_gallery_path %>">Create New Gallery</a>
                <hr>
                <%= link_to('Log Out', logout_path, class: 'dropdown-item', data: {confirm: 'Are you sure you want to log out?'})%>
              </div>
            </div>

          <%# If User is not logged in: %>
          <% else %>
            <%= link_to('Log In', login_path, class: 'btn btn-secondary') %>
          <% end %>

        </div>
      </div>
    </header>

    <main role="main">
      <%= yield %>
    </main>

    <footer class="text-muted">
      <div class="container mt-3">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Rails Gallery by Paul Thompson</p>
      </div>
    </footer>
  </body>
</html>